// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbnd4Do2sFLjMPgAxKv4fgVe_WUeWvEV4',
    appId: '1:465320960739:web:1af6a237d27f936691dbd6',
    messagingSenderId: '465320960739',
    projectId: 'haajir-5675',
    authDomain: 'haajir-5675.firebaseapp.com',
    storageBucket: 'haajir-5675.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpR-w_RQW0y59smCy-qby7_RQN6CqxpPY',
    appId: '1:465320960739:android:c0f4eddfe3c20e2991dbd6',
    messagingSenderId: '465320960739',
    projectId: 'haajir-5675',
    storageBucket: 'haajir-5675.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRPK4-E82TEnWuHffRtP41YcP9QjvOYPo',
    appId: '1:465320960739:ios:f9c7e16263b2a59491dbd6',
    messagingSenderId: '465320960739',
    projectId: 'haajir-5675',
    storageBucket: 'haajir-5675.firebasestorage.app',
    androidClientId: '465320960739-jvmvmrbk2udoj0akvblcsj5kipd2tb1m.apps.googleusercontent.com',
    iosClientId: '465320960739-3arut9pi053re3kohdrh2qkc40v0gbc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.haajir',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRPK4-E82TEnWuHffRtP41YcP9QjvOYPo',
    appId: '1:465320960739:ios:f9c7e16263b2a59491dbd6',
    messagingSenderId: '465320960739',
    projectId: 'haajir-5675',
    storageBucket: 'haajir-5675.firebasestorage.app',
    androidClientId: '465320960739-jvmvmrbk2udoj0akvblcsj5kipd2tb1m.apps.googleusercontent.com',
    iosClientId: '465320960739-3arut9pi053re3kohdrh2qkc40v0gbc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.haajir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbnd4Do2sFLjMPgAxKv4fgVe_WUeWvEV4',
    appId: '1:465320960739:web:46047a5c645410d591dbd6',
    messagingSenderId: '465320960739',
    projectId: 'haajir-5675',
    authDomain: 'haajir-5675.firebaseapp.com',
    storageBucket: 'haajir-5675.firebasestorage.app',
  );
}
